### PR TITLE
Change icon status area position

### PR DESCRIPTION
**Pull request by oqo0**
## Pull request summary:
I'm constantly changing the language and I don't want to see the icon of this extension next to it.
If the icon of this extension is to the right of the language icon, then this is not entirely intuitive. I suggest shifting the icon to the left to solve this problem.

## UI related changes:
change

### CODE REVIEW

**Comment by stuarthayhurst** [comment]
How about this as a setting? I'll backport the settings code from one of my other extensions later if that sounds good :)

**Comment by oqo0** [comment]
Great idea. Thank you.

**Comment by stuarthayhurst** [comment]
That's the UI and build system changes implemented, the new setting has functionality, but needs the extension to be toggled on and off for it to take effect for now until I fix that

**Comment by stuarthayhurst** [comment]
If you're happy with this, I'll merge :)
If you want to test it, it should be the usual `make build install`, restart GNOME and then check the settings

**Comment by oqo0** [comment]
I tested it and it works just great. Nice job. Cheers.

**Pull request merged**
