### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by daPhipz**
I updated the German translation to make it compliant with the guidelines of the German l10n team for GNOME. I added some metadata to the Dutch translation as well.

If you want, you can ping me whenever there's something new to translate - also for other projects. I'm always happy to help out ;)

### CODE REVIEW

**Comment by stuarthayhurst** [comment]
Thanks, I didn't want to bother you if you hadn't volunteered with the project :)

**Comment by stuarthayhurst** [comment]
Since I don't speak German, I'll merge whichever translation you two agree on, just let me know with an @ mention if I miss it :)

**Comment by daPhipz** [comment]
> Please take a look in Gnome settings (Geman UI): Datenschutz -> Ortungsdienste. I chose this translation to match the german translation used in Gnome settings.

Oh that's weird. I booted the Ubuntu 21.10 Daily image in order to check whether the string was correct, and I got this (as you can see, Ubuntu 21.10 has version `40.0` of `gnome-control-center`):

Bildschirmfoto von 2021-09-21 20-15-21

To be fair, the translation might have changed in the 41 dev cycle, that may be why I didn't catch it.

I don't see a problem with "Auf Voreinstellungen zurücksetzen", which you claim to be too long. I'm not saying that you are wrong there, it could just be my display dimensions or the fact that I am using Ubuntu 20.04 with GNOME 3.38 and not 40/41. Here's a screenshot:

popup

Does your experience differ from mine, @Etamuk?

I will definitely revert the "Ortungsdienste" change, and depending on what your experience is, also the second change. Thanks for reporting it, it is always beneficial to have four eyes to look at things ;)

**Comment by Etamuk** [comment]
Everything is fine :-) 

I am using Fedora 34 GNOME 40.4.0 also with gnome-control-center 40.0. Weired
Maybe Ubuntu uses an other translation source, but I don´t think so.

Concerning the question about "Auf Voreinstellungen zurücksetzen":

Here are two results on my screen:
Bildschirmfoto von 2021-09-22 14-28-30

Bildschirmfoto von 2021-09-22 14-47-22


As you can see there is no really problem with that supposed long translation. Sorry for that agitation. 

So I agree to translate it to "Auf Voreinstellungen zurücksetzen".
But I think "Ortungsdienste" should stay as actual translation (at this moment). Let´s see what the next final Gnome version (41) uses as translation. You can change it when there is "Standortdienste" as default. 

Sorry again.

**Comment by daPhipz** [comment]
No hard feelings, @Etamuk :heart: 
I agree with you that "Ortungsdienste" is the better translation - it sounds better as well, IMO ;) Expect a PR shortly, @stuarthayhurst.
If this string changes with 41, we can still revert this change. :+1:

**Comment by Etamuk** [comment]
That sounds good. :smile:
Thanks for that fair discussion.

**Pull request merged**
